services:
  strapi:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      APP_KEYS: ${APP_KEYS}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./public:/opt/app/public
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
    ports:
      - "1338:1337"
    depends_on:
      - postgres

  postgres:
    platform: linux/amd64
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  uploads_data:
  postgres_data:
